import { css } from '@emotion/react'
import { useState, useRef, useEffect } from 'react'
import jsPDF from 'jspdf'
import { downloadExport, type ExportMessage } from '../../utils/chatExport'

interface MessageExportMenuProps {
  message: ExportMessage
  disabled?: boolean
}

const MessageExportMenu: React.FC<MessageExportMenuProps> = ({ message, disabled = false }) => {
  const [isOpen, setIsOpen] = useState(false)
  const menuRef = useRef<HTMLDivElement>(null)

  // Generate meaningful filename from message content
  const generateFilename = (): string => {
    // Get first 50 characters of content, clean it up
    let filename = message.content.slice(0, 50).trim()

    // Remove special characters and replace spaces with hyphens
    filename = filename
      .toLowerCase()
      .replace(/[^\w\s-]/g, '') // Remove special chars
      .replace(/\s+/g, '-')      // Replace spaces with hyphens
      .replace(/-+/g, '-')       // Replace multiple hyphens with single
      .replace(/^-|-$/g, '')     // Remove leading/trailing hyphens

    // If filename is empty or too short, use a default
    if (filename.length < 3) {
      filename = message.type === 'user' ? 'user-message' : 'assistant-response'
    }

    // Add timestamp for uniqueness
    const timestamp = new Date().toISOString().split('T')[0]
    return `${filename}-${timestamp}`
  }

  // Close menu when clicking outside
  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (menuRef.current && !menuRef.current.contains(event.target as Node)) {
        setIsOpen(false)
      }
    }

    if (isOpen) {
      document.addEventListener('mousedown', handleClickOutside)
      return () => document.removeEventListener('mousedown', handleClickOutside)
    }
  }, [isOpen])

  const exportAsPDF = () => {
    const doc = new jsPDF()
    const pageWidth = doc.internal.pageSize.getWidth()
    const pageHeight = doc.internal.pageSize.getHeight()
    const margin = 20
    const maxWidth = pageWidth - (margin * 2)

    // Header with gradient background (simulated with purple)
    doc.setFillColor(111, 46, 255) // #6F2EFF
    doc.rect(0, 0, pageWidth, 40, 'F')

    // Title
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(20)
    doc.setFont('helvetica', 'bold')
    doc.text('Agent Response Export', pageWidth / 2, 25, { align: 'center' })

    // Reset text color
    doc.setTextColor(0, 0, 0)

    // Timestamp
    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.text(`Exported on ${new Date().toLocaleString()}`, margin, 50)

    // Role label
    let y = 60
    doc.setFontSize(12)
    doc.setFont('helvetica', 'bold')
    const roleText = message.type === 'user' ? 'You' : 'Assistant'
    doc.text(`${roleText}:`, margin, y)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    doc.text(message.timestamp.toLocaleString(), margin + 20, y)

    // Content
    y += 10
    doc.setFontSize(11)
    const lines = doc.splitTextToSize(message.content, maxWidth)

    lines.forEach((line: string) => {
      if (y > pageHeight - margin) {
        doc.addPage()
        y = margin
      }
      doc.text(line, margin, y)
      y += 6
    })

    // Activities (if any)
    if (message.activities && message.activities.length > 0) {
      y += 5
      if (y > pageHeight - margin - 20) {
        doc.addPage()
        y = margin
      }
      doc.setFont('helvetica', 'bold')
      doc.text('Activities:', margin, y)
      y += 7
      doc.setFont('helvetica', 'normal')

      message.activities.forEach((activity: string) => {
        if (y > pageHeight - margin) {
          doc.addPage()
          y = margin
        }
        doc.text(`• ${activity}`, margin + 5, y)
        y += 6
      })
    }

    // Footer
    const footerY = pageHeight - 15
    doc.setFontSize(9)
    doc.setTextColor(102, 102, 102)
    doc.text('Generated by Paid Media Suite - Growth Studio', pageWidth / 2, footerY, { align: 'center' })

    // Save PDF
    const filename = generateFilename()
    doc.save(`${filename}.pdf`)
    setIsOpen(false)
  }

  const exportAsMarkdown = () => {
    const roleText = message.type === 'user' ? '🧑 **You**' : '🤖 **Assistant**'
    let content = `# Agent Response Export\n\n`
    content += `*Exported on ${new Date().toLocaleString()}*\n\n`
    content += `---\n\n`
    content += `### ${roleText}\n`
    content += `*${message.timestamp.toLocaleString()}*\n\n`
    content += `${message.content}\n\n`

    if (message.activities && message.activities.length > 0) {
      content += `**Activities:**\n\n`
      message.activities.forEach(activity => {
        content += `- ${activity}\n`
      })
      content += '\n'
    }

    content += `---\n\n`
    content += `*Generated by Paid Media Suite - Growth Studio*\n`

    const filename = generateFilename()
    downloadExport(content, `${filename}.md`, 'text/markdown')
    setIsOpen(false)
  }

  const exportAsText = () => {
    const roleText = message.type === 'user' ? 'You' : 'Assistant'
    let content = `Agent Response Export\n`
    content += `${'='.repeat(50)}\n\n`
    content += `Exported on ${new Date().toLocaleString()}\n\n`
    content += `${roleText}:\n`
    content += `[${message.timestamp.toLocaleString()}]\n\n`
    content += `${message.content}\n\n`

    if (message.activities && message.activities.length > 0) {
      content += `Activities:\n`
      message.activities.forEach(activity => {
        content += `  - ${activity}\n`
      })
      content += '\n'
    }

    content += `${'-'.repeat(50)}\n\n`
    content += `Generated by Paid Media Suite - Growth Studio\n`

    const filename = generateFilename()
    downloadExport(content, `${filename}.txt`, 'text/plain')
    setIsOpen(false)
  }

  const exportAsJSON = () => {
    const exportData = {
      exportedAt: new Date().toISOString(),
      message: {
        type: message.type,
        content: message.content,
        timestamp: message.timestamp.toISOString(),
        ...(message.activities && { activities: message.activities })
      }
    }

    const content = JSON.stringify(exportData, null, 2)
    const filename = generateFilename()
    downloadExport(content, `${filename}.json`, 'application/json')
    setIsOpen(false)
  }

  const exportAsHTML = () => {
    const roleText = message.type === 'user' ? '🧑 You' : '🤖 Assistant'
    const roleClass = message.type === 'user' ? 'user' : 'assistant'
    const escapeHtml = (text: string): string => {
      const div = document.createElement('div')
      div.textContent = text
      return div.innerHTML
    }

    let html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Agent Response Export</title>
  <style>
    body {
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      max-width: 800px;
      margin: 0 auto;
      padding: 20px;
      background-color: #f5f5f5;
    }
    .header {
      text-align: center;
      margin-bottom: 30px;
      padding: 20px;
      background: linear-gradient(135deg, #6F2EFF 0%, #1957DB 100%);
      color: white;
      border-radius: 8px;
    }
    .message {
      margin-bottom: 20px;
      padding: 15px;
      border-radius: 8px;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }
    .user {
      background-color: #E8F4F8;
      border-left: 4px solid #1957DB;
    }
    .assistant {
      background-color: #F3E8FF;
      border-left: 4px solid #6F2EFF;
    }
    .role {
      font-weight: bold;
      margin-bottom: 8px;
      color: #333;
    }
    .timestamp {
      font-size: 0.85em;
      color: #666;
      margin-left: 10px;
    }
    .content {
      line-height: 1.6;
      color: #444;
      white-space: pre-wrap;
    }
    .activities {
      margin-top: 10px;
      padding: 10px;
      background-color: rgba(0,0,0,0.05);
      border-radius: 4px;
    }
    .activities h4 {
      margin: 0 0 8px 0;
      font-size: 0.9em;
      color: #666;
    }
    .activities ul {
      margin: 0;
      padding-left: 20px;
    }
    .footer {
      text-align: center;
      margin-top: 30px;
      padding: 15px;
      color: #666;
      font-size: 0.9em;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>Agent Response Export</h1>
    <p>Exported on ${new Date().toLocaleString()}</p>
  </div>
  <div class="messages">
    <div class="message ${roleClass}">
      <div class="role">
        ${roleText}
        <span class="timestamp">${message.timestamp.toLocaleString()}</span>
      </div>
      <div class="content">${escapeHtml(message.content)}</div>`

    if (message.activities && message.activities.length > 0) {
      html += `
      <div class="activities">
        <h4>Activities:</h4>
        <ul>`
      message.activities.forEach(activity => {
        html += `
          <li>${escapeHtml(activity)}</li>`
      })
      html += `
        </ul>
      </div>`
    }

    html += `
    </div>
  </div>
  <div class="footer">
    <p>Generated by Paid Media Suite - Growth Studio</p>
  </div>
</body>
</html>`

    const filename = generateFilename()
    downloadExport(html, `${filename}.html`, 'text/html')
    setIsOpen(false)
  }

  return (
    <div ref={menuRef} css={css`
      position: relative;
      display: inline-block;
    `}>
      <button
        onClick={() => setIsOpen(!isOpen)}
        disabled={disabled}
        title="Export this message"
        css={css`
          display: flex;
          align-items: center;
          justify-content: center;
          padding: 6px;
          background-color: transparent;
          border: 1px solid transparent;
          border-radius: 6px;
          color: #878F9E;
          cursor: ${disabled ? 'not-allowed' : 'pointer'};
          opacity: ${disabled ? '0.5' : '0.7'};
          transition: all 0.2s;

          &:hover:not(:disabled) {
            background-color: #F9FBFF;
            border-color: #DCE1EA;
            color: #6F2EFF;
            opacity: 1;
          }

          svg {
            width: 16px;
            height: 16px;
          }
        `}
      >
        <ExportIcon />
      </button>

      {isOpen && (
        <div css={css`
          position: absolute;
          top: calc(100% + 8px);
          right: 0;
          background-color: white;
          border: 1px solid #DCE1EA;
          border-radius: 8px;
          box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
          padding: 8px;
          min-width: 180px;
          z-index: 1000;
        `}>
          <div css={css`
            display: flex;
            flex-direction: column;
            gap: 4px;
          `}>
            <ExportOption
              icon="📕"
              label="PDF (.pdf)"
              description="Portable document"
              onClick={exportAsPDF}
            />
            <ExportOption
              icon="📝"
              label="Markdown (.md)"
              description="Rich text format"
              onClick={exportAsMarkdown}
            />
            <ExportOption
              icon="📄"
              label="Plain Text (.txt)"
              description="Simple text format"
              onClick={exportAsText}
            />
            <ExportOption
              icon="🌐"
              label="HTML (.html)"
              description="Web page format"
              onClick={exportAsHTML}
            />
            <ExportOption
              icon="📊"
              label="JSON (.json)"
              description="Data format"
              onClick={exportAsJSON}
            />
          </div>
        </div>
      )}
    </div>
  )
}

interface ExportOptionProps {
  icon: string
  label: string
  description: string
  onClick: () => void
}

const ExportOption: React.FC<ExportOptionProps> = ({ icon, label, description, onClick }) => {
  return (
    <button
      onClick={onClick}
      css={css`
        display: flex;
        align-items: center;
        gap: 12px;
        padding: 10px 12px;
        background-color: transparent;
        border: none;
        border-radius: 6px;
        cursor: pointer;
        transition: all 0.2s;
        text-align: left;
        width: 100%;

        &:hover {
          background-color: #F9FBFF;
        }
      `}
    >
      <span css={css`
        font-size: 20px;
        min-width: 20px;
      `}>
        {icon}
      </span>
      <div css={css`
        flex: 1;
      `}>
        <div css={css`
          font-family: 'Figtree', sans-serif;
          font-size: 14px;
          font-weight: 500;
          color: #212327;
          margin-bottom: 2px;
        `}>
          {label}
        </div>
        <div css={css`
          font-family: 'Figtree', sans-serif;
          font-size: 12px;
          color: #878F9E;
        `}>
          {description}
        </div>
      </div>
    </button>
  )
}

const ExportIcon = () => (
  <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
    <path d="M8 2V10M8 2L5 5M8 2L11 5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
    <path d="M2 10V13C2 13.5523 2.44772 14 3 14H13C13.5523 14 14 13.5523 14 13V10" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/>
  </svg>
)

export default MessageExportMenu
